version: '3.7'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=9mREsvXDs9Gk89Ef