version: '3.7'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
